const fs = require('fs');
const path = require('path');

const configPath = path.join(__dirname, '../config/tool-constants.json');
const data = JSON.parse(fs.readFileSync(configPath, 'utf8'));

// CoC Yield Guides
const cocGuides = data.tools['coc-yield'].guides;

cocGuides['cash-on-cash-yield-proofs'].content = [
  "### Cash-on-Cash (CoC) Yield Defined",
  "Cash-on-Cash yield is arguably the most critical metric for active real estate investors. It measures the pure cash return on the actual cash invested in a property over a one-year period.",
  "Unlike Internal Rate of Return (IRR) or Total ROI, CoC ignores future property appreciation, loan principal paydown, and complex depreciation tax benefits. It answers one simple question: *'If I put $100,000 into this deal today, how much actual cash lands in my bank account over the next 12 months?'*",
  "### The Mathematical Formula",
  "The formula requires isolating the net cash flow generated specifically from operations:",
  "\\[ \\text{Cash-on-Cash Yield} = \\frac{\\text{Annual Pre-Tax Cash Flow}}{\\text{Total Cash Invested}} \\times 100 \\]",
  "### Component Breakdown",
  "1. **Annual Pre-Tax Cash Flow**: This is the Net Operating Income (NOI) minus the annual debt service payments (both mortgage principal and interest).",
  "2. **Total Cash Invested**: This is not just the down payment. It includes the down payment, loan origination fees, closing costs, and any immediate capital expenditures (CapEx) required to get the property operational (like replacing a roof immediately after purchase)."
];
cocGuides['cash-on-cash-yield-proofs'].faqs = [
  { question: "Why doesn't Cash-on-Cash yield include property appreciation?", answer: "Cash-on-Cash yield specifically measures liquid cash velocity. Appreciation only provides unrealized paper wealth until the property is sold or refinanced." },
  { question: "Is a 10% Cash-on-Cash return good?", answer: "A 10% CoC return is generally considered very strong in modern commercial real estate, as it means your liquid investment will completely pay for itself in exactly 10 years, ignoring all other equity growth." },
  { question: "Do closing costs factor into Cash-on-Cash yield?", answer: "Yes. Every dollar you spend out-of-pocket to acquire the property (including closing costs and immediate repairs) must be included in the 'Total Cash Invested' denominator." }
];

cocGuides['dscr-guidelines-banks'].content = [
  "### What is DSCR?",
  "The Debt Service Coverage Ratio (DSCR) is the primary risk-assessment metric used by commercial lenders. It measures a commercial property's ability to cover its debt payments using exclusively its own operating income.",
  "Unlike residential mortgages, which evaluate the borrower's personal W-2 income and DTI, commercial loans evaluate the *property's* income. If the property cannot sustain itself, the bank assumes heavy risk.",
  "### The Formula",
  "\\[ \\text{DSCR} = \\frac{\\text{Net Operating Income (NOI)}}{\\text{Annual Debt Service}} \\]",
  "### Lenders' Threshold Tiers",
  "- **DSCR < 1.0**: The property is bleeding cash. It does not generate enough income to cover the mortgage. Banks will immediately reject these loans unless the borrower is bringing massive cash reserves.",
  "- **DSCR = 1.0**: Break-even. Every dollar of profit goes straight to the bank. Still too risky for lenders.",
  "- **DSCR = 1.15 - 1.20**: This is the minimum threshold for 'safe' asset classes like stabilized multi-family apartment buildings.",
  "- **DSCR = 1.25 - 1.35**: The standard threshold for riskier assets like retail strip centers, office spaces, or mixed-use properties.",
  "- **DSCR > 1.40**: Highly conservative. Indicates immense cash flow buffers and ensures the borrower will receive the lowest possible interest rates."
];
cocGuides['dscr-guidelines-banks'].faqs = [
  { question: "Can I get a commercial loan with a DSCR below 1.0?", answer: "Generally, no traditional bank will touch a negative DSCR. You would need to use hard-money lenders or bridge loans at much higher interest rates until the property is stabilized." },
  { question: "Does DSCR include personal income?", answer: "No. DSCR is calculated strictly on the Net Operating Income (NOI) generated by the property itself. Commercial lending is asset-based." },
  { question: "How can I improve a property's DSCR?", answer: "You can improve DSCR by increasing the NOI (raising rents, billing back utilities) or by decreasing the debt service (putting down a larger down payment to shrink the loan amount)." }
];

cocGuides['cap-rate-vs-coc-yield'].content = [
  "### Capitalization (Cap) Rate: The Unleveraged Metric",
  "The Cap Rate evaluates a property's return on investment *assuming the asset is purchased entirely in cash* (zero debt). It is primarily used to evaluate the market value and risk premium of the asset relative to other properties in the area.",
  "\\[ \\text{Cap Rate} = \\frac{\\text{Net Operating Income (NOI)}}{\\text{Purchase Price}} \\times 100 \\]",
  "A low cap rate (e.g., 4%) indicates a safe, highly desirable market (like prime NYC retail). A high cap rate (e.g., 10%) indicates higher risk or less desirable locations.",
  "### Cash-on-Cash Yield: The Leveraged Metric",
  "CoC yield evaluates a leveraged return. It fluctuates based on your financing structure: the loan interest rate, the loan-to-value (LTV) ratio, and your out-of-pocket costs.",
  "### Leveraged Arbitrage (Positive Leverage)",
  "The magic of commercial real estate occurs through positive leverage. When the Cap Rate of a property is higher than the interest rate of the bank loan used to buy it, adding debt *increases* your CoC yield.",
  "For example, buying a property at an 8% Cap Rate using a mortgage with a 5% interest rate creates a 3% spread. The bank is financing your asset cheaper than the asset yields, rocketing your Cash-on-Cash return into the double digits."
];
cocGuides['cap-rate-vs-coc-yield'].faqs = [
  { question: "What is the difference between Cap Rate and Cash-on-Cash Yield?", answer: "Cap Rate assumes you bought the property with 100% cash. Cash-on-Cash yield factors in your mortgage payments and measures the return on your actual out-of-pocket down payment." },
  { question: "What is positive leverage in real estate?", answer: "Positive leverage occurs when the Cap Rate of a property is higher than the interest rate of your mortgage, meaning borrowing money actually increases your overall percentage return." },
  { question: "Is a higher Cap Rate always better?", answer: "Not necessarily. A very high Cap Rate usually indicates significant risk, such as a bad neighborhood, an aging building requiring heavy maintenance, or a tenant likely to default." }
];

cocGuides['commercial-lease-structures-guide'].content = [
  "### Types of Commercial Leases",
  "Unlike residential leases where the landlord pays almost all operating expenses, commercial lease structures dictate which expenses are passed through to the tenant. This directly determines the predictability of the landlord's Net Operating Income (NOI).",
  "### 1. Triple Net (NNN) Lease",
  "In a Triple Net lease, the tenant is responsible for virtually all property operating expenses on top of their base rent. The three 'Nets' are:",
  "- **N1**: Property Taxes",
  "- **N2**: Building Insurance",
  "- **N3**: Common Area Maintenance (CAM) & Repairs",
  "NNN leases are highly favored by passive investors because the landlord has minimal expense fluctuation, creating a highly stable and predictable Cap Rate.",
  "### 2. Gross Lease (Full Service)",
  "The tenant pays a single, flat monthly rent. The landlord is responsible for paying all taxes, insurance, utilities, and maintenance out of that rent.",
  "While Gross leases are simpler for tenants to budget, they carry massive risk for landlords. If property taxes spike or a harsh winter triples the heating bill, the landlord's NOI decreases directly.",
  "### 3. Modified Gross (Double Net / NN)",
  "A hybrid approach where the tenant and landlord share operating expenses. Often, the tenant pays Base Rent plus utilities and interior maintenance, while the landlord covers roof repairs, structural issues, and property taxes."
];
cocGuides['commercial-lease-structures-guide'].faqs = [
  { question: "What does NNN stand for?", answer: "NNN stands for Triple Net. It refers to the three primary operating expenses a tenant must pay: Property Taxes, Insurance, and Maintenance." },
  { question: "Why do investors prefer NNN leases?", answer: "Investors prefer NNN leases because they provide a passive, predictable income stream. If a roof breaks or taxes increase, the tenant pays for it, protecting the investor's profit margin." },
  { question: "What is a Modified Gross lease?", answer: "It is a compromise structure where the landlord and tenant share operating costs. For example, the tenant might pay for utilities and janitorial services, while the landlord pays property taxes." }
];

// JSON Parser Guides
const jpGuides = data.tools['json-parser'].guides;
jpGuides['json-syntax-and-formatting-rules'].content = [
  "### The Strict Rules of JSON",
  "JavaScript Object Notation (JSON) is the undisputed king of lightweight data-interchange formats. However, because it is designed for rapid machine parsing, it enforces strict syntax rules that easily trip up developers:",
  "1. **Double Quotes Only**: All keys and string values must be enclosed in double quotes (`\"`). Single quotes (`'`) or backticks (`` ` ``) are invalid and will cause immediate parsing failures.",
  "2. **No Trailing Commas**: Unlike standard JavaScript objects, JSON strictly forbids a trailing comma after the final property in an object or the final element in an array.",
  "3. **Data Types**: Allowed data types are String, Number, Object (JSON object), Array, Boolean, and Null. You cannot serialize Functions, `undefined`, or Date objects (Dates must be converted to ISO 8601 strings).",
  "### The Cost of Syntax Errors",
  "A single misplaced comma in a massive JSON payload will cause `JSON.parse()` to throw a fatal exception. In edge environments or microservices, unhandled parse exceptions can crash entire node processes."
];
jpGuides['json-syntax-and-formatting-rules'].faqs = [
  { question: "Can I use single quotes in JSON?", answer: "No. JSON syntax strictly requires double quotes for all keys and string values. Single quotes will cause a parsing error." },
  { question: "Does JSON support comments?", answer: "No. Standard JSON does not support comments (like // or /* */). If you need comments for configuration files, consider using JSONC or YAML." },
  { question: "Can I store a Date object in JSON?", answer: "JSON does not have a native Date type. Dates must be serialized into Strings (usually ISO 8601 format) before being placed in a JSON payload." }
];

jpGuides['json-vs-xml-performance'].content = [
  "### Why JSON Won the API War",
  "For decades, XML (eXtensible Markup Language) was the heavy, verbose standard for APIs (SOAP). However, REST APIs overwhelmingly shifted to JSON for two critical performance reasons:",
  "1. **Payload Size**: XML requires opening and closing tags for every single node (e.g., `<name>John</name>`). JSON uses lightweight key-value syntax (`\"name\":\"John\"`). This drastically reduces the byte size of data transferred over the wire.",
  "2. **Parsing Velocity**: Browsers parse JSON natively using highly optimized C++ `JSON.parse()` routines directly into memory arrays and objects. Parsing XML requires traversing a complex Document Object Model (DOM) tree, which consumes significantly more CPU cycles.",
  "### Minification for Edge Environments",
  "When transmitting JSON over a network, human readability is irrelevant. Stripping whitespace, line breaks, and indentation from JSON payloads (minification) before transit can reduce the file size by 15-30% depending on the nesting depth.",
  "In high-traffic edge APIs, this size reduction directly translates to lower egress bandwidth costs and faster client-side rendering times."
];
jpGuides['json-vs-xml-performance'].faqs = [
  { question: "Why is JSON faster to parse than XML?", answer: "JSON maps directly to native data structures (objects and arrays) in JavaScript and other languages. XML requires a complex DOM parser to traverse tags and attributes." },
  { question: "What is JSON minification?", answer: "Minification is the process of removing all unnecessary whitespace, tabs, and line breaks from a JSON payload to reduce its file size for faster network transmission." },
  { question: "Is JSON always better than XML?", answer: "JSON is vastly superior for web APIs. However, XML is still used in enterprise legacy systems, document markup (like SVG or RSS), and scenarios requiring strict schema validation via XSD." }
];

// NNN Calculator Guides
const nnnGuides = data.tools['nnn-calculator'].guides;
nnnGuides['nnn-vs-gross-lease'].content = [
  "### The Triple Net (NNN) Advantage for Landlords",
  "In a Triple Net lease, the tenant pays a lower Base Rent but assumes responsibility for the 'three nets': Property Taxes, Building Insurance, and Common Area Maintenance (CAM).",
  "This structure is highly prized by Commercial Real Estate (CRE) investors because it creates a 'bond-like' income stream. The landlord's profit margin is locked in. If local property taxes double next year, the tenant absorbs the cost entirely.",
  "### Gross Leases (Full Service)",
  "A Gross Lease bundles all operating expenses into one fixed rent payment. The tenant writes a single check every month.",
  "While tenants love Gross leases for their budgeting predictability, landlords hate them. If a harsh winter triples the snow-removal and heating costs, the landlord's Net Operating Income (NOI) plummets because they cannot pass those extra costs onto the tenant.",
  "### Base Year Stop (The Compromise)",
  "In office buildings, landlords often use a 'Base Year Stop'. The landlord pays all expenses during the first year of the lease (the Base Year). In subsequent years, if expenses increase above the Base Year level, the tenant must pay the difference. This protects the landlord from inflation while giving the tenant initial stability."
];
nnnGuides['nnn-vs-gross-lease'].faqs = [
  { question: "Who pays for a new roof in a Triple Net lease?", answer: "Typically, the tenant does. However, major structural replacements (like a roof or foundation) are heavily negotiated. Often, landlords handle structural issues while tenants handle everyday maintenance." },
  { question: "Why is base rent lower in an NNN lease?", answer: "Because the tenant takes on the massive financial risk of fluctuating property taxes, insurance, and maintenance. The lower base rent compensates for this unpredictable overhead." },
  { question: "What is a Base Year Stop?", answer: "It is a lease clause where the landlord pays operating expenses up to the amount incurred in the first year of the lease. Any cost increases in future years are passed onto the tenant." }
];

nnnGuides['understanding-cam-charges'].content = [
  "### What are CAM Fees?",
  "Common Area Maintenance (CAM) charges cover the cost of maintaining shared spaces in a commercial property (like a retail strip center or office park).",
  "These fees are distributed proportionally based on the square footage each tenant occupies. If you rent 2,000 sq ft in a 10,000 sq ft plaza, you are responsible for 20% of the plaza's total CAM costs (your pro-rata share).",
  "### Typical CAM Inclusions",
  "- Parking lot sweeping, repaving, and snow removal.",
  "- Landscaping, irrigation, and exterior lighting.",
  "- Security patrols and shared alarm monitoring.",
  "- Janitorial services for common lobbies, elevators, and bathrooms.",
  "- Water, trash, and sewer utilities for shared spaces.",
  "### Negotiating CAM Caps",
  "Tenants should aggressively negotiate a 'CAM Cap'. This is a contractual limit on how much CAM fees can increase year-over-year (typically capped at 3% to 5%).",
  "Without a cap, an aggressive landlord could decide to completely redesign the landscaping and repave the entire parking lot, passing a massive, unexpected bill to the tenants."
];
nnnGuides['understanding-cam-charges'].faqs = [
  { question: "What does Pro-Rata share mean?", answer: "Pro-rata share is the percentage of the building you occupy. It determines your portion of the CAM fees. If you occupy 10% of the building, you pay 10% of the total maintenance bill." },
  { question: "Are property management fees included in CAM?", answer: "Yes, landlords typically include the fee they pay to the property management company (often 3% to 5% of gross rents) within the CAM charges passed to tenants." },
  { question: "What is a CAM Cap?", answer: "A CAM cap limits the annual percentage increase of maintenance fees passed to the tenant. It protects tenants from sudden, massive spikes in operating expenses." }
];

fs.writeFileSync(configPath, JSON.stringify(data, null, 2));
console.log('CoC, JSON, NNN guides patched.');
